[project]
name = "aegis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "binance-sdk-spot>=6.0.0",
    "redis>=7.1.0",
]
